[[autossh]]
arch = "aarch64"
git-tree-sha1 = "4cb2b45cdf363c654e45f5c6cc055a3436807641"
os = "macos"

    [[autossh.download]]
    sha256 = "52fbbac609da63e9a09f13c1604551edb39e57f95c1a748a1e3a5b81455ee7ee"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.aarch64-apple-darwin.tar.gz"
[[autossh]]
arch = "aarch64"
git-tree-sha1 = "fd8e268a1e9e072b6c665e6f8fddecb9b3897107"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "afde007042f37231e40735b80e2fbca467162d685d466b049c52946dee2715ba"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.aarch64-linux-gnu.tar.gz"
[[autossh]]
arch = "aarch64"
git-tree-sha1 = "4346f76cf8a64e124390817b387feee9e583e0ce"
libc = "musl"
os = "linux"

    [[autossh.download]]
    sha256 = "b7b5e9252590fe527822360df3c42aa7bcdf60b54645881316dbd6946f4dea28"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.aarch64-linux-musl.tar.gz"
[[autossh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "029c4692ffcaadcab925ed2f1227ae70c458db2b"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "581c7787d0aba469d9ed36895f32cf96bffb184b343e93c6c5929dec8a1d5038"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.armv6l-linux-gnueabihf.tar.gz"
[[autossh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f31f22451898e598976da7de0801dcb528e70e4"
libc = "musl"
os = "linux"

    [[autossh.download]]
    sha256 = "8ba5a3cb614a300c4bf970f2e3cf009bdb6376ebb292d2db88fe6052dde3f795"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.armv6l-linux-musleabihf.tar.gz"
[[autossh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2b6e477ad3e333cc9ea995a3009c7ec58685c42"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "49965e03dbc81e30699cefc24bf0c97a6a3897bf5b693f4641e6461c094de683"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[autossh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1414022fe54249065c65dd2aebf4d2843e732ae4"
libc = "musl"
os = "linux"

    [[autossh.download]]
    sha256 = "b88c14abdb42ae8cf5ed692e578d5e25bd21c410c4f17852903868b90c52d39e"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[autossh]]
arch = "i686"
git-tree-sha1 = "c91b8ae0cdf7952cc3ac297026b3bfb7ba78af2a"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "1de66559078bf5877d7179c34fbbd8bbae85dd02bce378db1f5fdf4264da0697"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.i686-linux-gnu.tar.gz"
[[autossh]]
arch = "i686"
git-tree-sha1 = "3bad0a7cff62cd445e2e681cd7c62a1059195cbe"
libc = "musl"
os = "linux"

    [[autossh.download]]
    sha256 = "093a20e7ca28dca87890bc4af4c297757d7f62e111200d185b946dc836f8e034"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.i686-linux-musl.tar.gz"
[[autossh]]
arch = "powerpc64le"
git-tree-sha1 = "f1af64a0b4ed51a1450c9ddca7fe8a6aaf47d1ac"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "ef306961a2b30bd3c75fc3e237fde89559062ac22630650b1d05ef8d2f916788"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[autossh]]
arch = "x86_64"
git-tree-sha1 = "1514bd20c89212d57fe02de3c86d205b2f289e24"
os = "macos"

    [[autossh.download]]
    sha256 = "445e2a0df1d67d0d70625edd608692d142ba6e94d20b4594d49ccffacbfbee33"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.x86_64-apple-darwin.tar.gz"
[[autossh]]
arch = "x86_64"
git-tree-sha1 = "f4d8210f59ff8b21f2fcba665a7979995cac1c5e"
libc = "glibc"
os = "linux"

    [[autossh.download]]
    sha256 = "1df4117caf92f56ab61a47e7f45bb79174d1eb3a56a935ccd51c54ec6c6d71b3"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.x86_64-linux-gnu.tar.gz"
[[autossh]]
arch = "x86_64"
git-tree-sha1 = "75e681883a47fd6732c9e0b5b32f1b88acee05b2"
libc = "musl"
os = "linux"

    [[autossh.download]]
    sha256 = "f29db01ae936111c177f4169dd94559ca2840eed4e33542fec7efcd8bbd73f32"
    url = "https://github.com/JuliaBinaryWrappers/autossh_jll.jl/releases/download/autossh-v1.4.0+0/autossh.v1.4.0.x86_64-linux-musl.tar.gz"
